Refactor/separate app from server
m4theuspereira-maker/template pull request #4
Opened 2023-07-07 19:03 UTC by ilmardanilo

Esta PR separa o app em um arquivo unico

2023-07-07 21:07 UTC, m4theuspereira-maker commented on src/app.ts
> +app.use("/", routes);
Basta tirar o "/"

2023-07-07 21:08 UTC, m4theuspereira-maker requested changes
basta tirar o /

2023-07-07 22:06 UTC, ilmardanilo commented on src/app.ts
> +app.use("/", routes);
feito

2023-07-08 13:21 UTC, m4theuspereira-maker approved these changes

2023-07-08 13:21 UTC, m4theuspereira-maker approved these changes

2023-07-08 13:22 UTC, merged